# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.3 on Wed Feb 15 08:52:50 2023
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyDialog(wx.Dialog):
	def __init__(self, *args, **kwds):
		# begin wxGlade: MyDialog.__init__
		kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE | wx.RESIZE_BORDER
		wx.Dialog.__init__(self, *args, **kwds)
		self.SetTitle("Calculadora")

		sizer_1 = wx.BoxSizer(wx.VERTICAL)

		grid_sizer_1 = wx.FlexGridSizer(1, 3, 0, 0)
		sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

		sizer_3 = wx.BoxSizer(wx.VERTICAL)
		grid_sizer_1.Add(sizer_3, 1, wx.EXPAND, 0)

		label_1 = wx.StaticText(self, wx.ID_ANY, "Valor 1")
		sizer_3.Add(label_1, 0, 0, 0)

		self.text_ctrl_1 = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.HSCROLL | wx.TE_CENTRE)
		sizer_3.Add(self.text_ctrl_1, 0, wx.EXPAND, 0)

		self.combo_box_1 = wx.ComboBox(self, wx.ID_ANY, choices=["Somar", "Subtrair"], style=wx.CB_DROPDOWN | wx.CB_READONLY)
		grid_sizer_1.Add(self.combo_box_1, 0, 0, 0)

		sizer_4 = wx.BoxSizer(wx.VERTICAL)
		grid_sizer_1.Add(sizer_4, 1, wx.EXPAND, 0)

		label_2 = wx.StaticText(self, wx.ID_ANY, "Valor 2")
		sizer_4.Add(label_2, 0, 0, 0)

		self.text_ctrl_2 = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.HSCROLL | wx.TE_CENTRE)
		sizer_4.Add(self.text_ctrl_2, 0, wx.EXPAND, 0)

		sz_calcularSair = wx.StdDialogButtonSizer()
		sizer_1.Add(sz_calcularSair, 0, wx.ALIGN_RIGHT | wx.ALL, 4)

		self.button_OK = wx.Button(self, wx.ID_OK, "")
		self.button_OK.SetDefault()
		sz_calcularSair.AddButton(self.button_OK)

		self.button_CANCEL = wx.Button(self, wx.ID_CANCEL, "")
		sz_calcularSair.AddButton(self.button_CANCEL)

		sz_calcularSair.Realize()

		self.SetSizer(sizer_1)
		sizer_1.Fit(self)

		self.SetAffirmativeId(self.button_OK.GetId())
		self.SetEscapeId(self.button_CANCEL.GetId())

		self.Layout()
		self.Centre()

		self.Bind(wx.EVT_BUTTON, self.do_calcular, self.button_OK)
		# end wxGlade

	def do_calcular(self, event):  # wxGlade: MyDialog.<event_handler>
		print("Event handler 'do_calcular' not implemented!")
		event.Skip()

# end of class MyDialog
